[package]
name = "tfgen"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
nalgebra = "0.33.2"
petgraph = "0.6.5"

[dev-dependencies]
approx = "0.5.1"
# nalgebra = { version = "0.33.2", features = ["debug"] }
